include::page$attributes.adoc[]
[[rsocket-annot-responders]]
== Annotated Responders

RSocket responders can be implemented as `@MessageMapping` and `@ConnectMapping` methods.
`@MessageMapping` methods handle individual requests while `@ConnectMapping` methods handle
connection-level events (setup and metadata push). Annotated responders are supported
symmetrically, for responding from the server side and for responding from the client side.



[[rsocket-annot-responders-server]]
=== Server Responders

To use annotated responders on the server side, add `RSocketMessageHandler` to your Spring
configuration to detect `@Controller` beans with `@MessageMapping` and `@ConnectMapping`
methods:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	@Configuration
	static class ServerConfig {

		@Bean
		public RSocketMessageHandler rsocketMessageHandler() {
			RSocketMessageHandler handler = new RSocketMessageHandler();
			handler.routeMatcher(new PathPatternRouteMatcher());
			return handler;
		}
	}
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	@Configuration
	class ServerConfig {

		@Bean
		fun rsocketMessageHandler() = RSocketMessageHandler().apply {
			routeMatcher = PathPatternRouteMatcher()
		}
	}
----

Then start an RSocket server through the Java RSocket API and plug the
`RSocketMessageHandler` for the responder as follows:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	ApplicationContext context = ... ;
	RSocketMessageHandler handler = context.getBean(RSocketMessageHandler.class);

	CloseableChannel server =
		RSocketFactory.receive()
			.acceptor(handler.responder())
			.transport(TcpServerTransport.create("localhost", 7000))
			.start()
			.block();
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	import org.springframework.beans.factory.getBean

	val context: ApplicationContext = ...
	val handler = context.getBean<RSocketMessageHandler>()

	val server = RSocketFactory.receive()
			.acceptor(handler.responder())
			.transport(TcpServerTransport.create("localhost", 7000))
			.start().awaitFirst()
----

`RSocketMessageHandler` supports
{gh-rsocket-extentions}/CompositeMetadata.md[composite] and
{gh-rsocket-extentions}/Routing.md[routing] metadata by default. You can set its
xref:rsocket:rsocket-metadata-extractor.adoc#rsocket-metadata-extractor[rsocket-metadata-extractor] if you need to switch to a
different mime type or register additional metadata mime types.

You'll need to set the `Encoder` and `Decoder` instances required for metadata and data
formats to support. You'll likely need the `spring-web` module for codec implementations.

By default `SimpleRouteMatcher` is used for matching routes via `AntPathMatcher`.
We recommend plugging in the `PathPatternRouteMatcher` from `spring-web` for
efficient route matching. RSocket routes can be hierarchical but are not URL paths.
Both route matchers are configured to use "." as separator by default and there is no URL
decoding as with HTTP URLs.

`RSocketMessageHandler` can be configured via `RSocketStrategies` which may be useful if
you need to share configuration between a client and a server in the same process:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	@Configuration
	static class ServerConfig {

		@Bean
		public RSocketMessageHandler rsocketMessageHandler() {
			RSocketMessageHandler handler = new RSocketMessageHandler();
			handler.setRSocketStrategies(rsocketStrategies());
			return handler;
		}

		@Bean
		public RSocketStrategies rsocketStrategies() {
			return RSocketStrategies.builder()
				.encoders(encoders -> encoders.add(new Jackson2CborEncoder))
				.decoders(decoders -> decoders.add(new Jackson2CborDecoder))
				.routeMatcher(new PathPatternRouteMatcher())
				.build();
		}
	}
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	@Configuration
	class ServerConfig {

		@Bean
		fun rsocketMessageHandler() = RSocketMessageHandler().apply {
			rSocketStrategies = rsocketStrategies()
		}

		@Bean
		fun rsocketStrategies() = RSocketStrategies.builder()
				.encoders { it.add(Jackson2CborEncoder()) }
				.decoders { it.add(Jackson2CborDecoder()) }
				.routeMatcher(PathPatternRouteMatcher())
				.build()
	}
----



[[rsocket-annot-responders-client]]
=== Client Responders

Annotated responders on the client side need to be configured in the
`RSocketRequester.Builder`. For details, see
xref:rsocket:rsocket-requester:rsocket-requester-client.adoc#rsocket-requester-client-responder[rsocket-requester-client-responder].



[[rsocket-annot-messagemapping]]
=== @MessageMapping

Once xref:rsocket:rsocket-annot-responders:rsocket-annot-responders-server.adoc#rsocket-annot-responders-server[server] or
xref:rsocket:rsocket-annot-responders:rsocket-annot-responders-client.adoc#rsocket-annot-responders-client[client] responder configuration is in place,
`@MessageMapping` methods can be used as follows:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	@Controller
	public class RadarsController {

		@MessageMapping("locate.radars.within")
		public Flux<AirportLocation> radars(MapRequest request) {
			// ...
		}
	}
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
@Controller
class RadarsController {

	@MessageMapping("locate.radars.within")
	fun radars(request: MapRequest): Flow<AirportLocation> {
		// ...
	}
}
----

The above `@MessageMapping` method responds to a Request-Stream interaction having the
route "locate.radars.within". It supports a flexible method signature with the option to
use the following method arguments:

[cols="1,3",options="header"]
|===
| Method Argument
| Description

| `@Payload`
| The payload of the request. This can be a concrete value of asynchronous types like
  `Mono` or `Flux`.

  *Note:* Use of the annotation is optional. A method argument that is not a simple type
  and is not any of the other supported arguments, is assumed to be the expected payload.

| `RSocketRequester`
| Requester for making requests to the remote end.

| `@DestinationVariable`
| Value extracted from the route based on variables in the mapping pattern, e.g.
  `@MessageMapping("find.radar.{id}")`.

| `@Header`
| Metadata value registered for extraction as described in xref:rsocket:rsocket-metadata-extractor.adoc#rsocket-metadata-extractor[rsocket-metadata-extractor].

| `@Headers Map<String, Object>`
| All metadata values registered for extraction as described in xref:rsocket:rsocket-metadata-extractor.adoc#rsocket-metadata-extractor[rsocket-metadata-extractor].

|===

The return value is expected to be one or more Objects to be serialized as response
payloads. That can be asynchronous types like `Mono` or `Flux`, a concrete value, or
either `void` or a no-value asynchronous type such as `Mono<Void>`.

The RSocket interaction type that an `@MessageMapping` method supports is determined from
the cardinality of the input (i.e. `@Payload` argument) and of the output, where
cardinality means the following:

[%autowidth]
[cols=2*,options="header"]
|===
| Cardinality
| Description

| 1
| Either an explicit value, or a single-value asynchronous type such as `Mono<T>`.

| Many
| A multi-value asynchronous type such as `Flux<T>`.

| 0
| For input this means the method does not have an `@Payload` argument.

  For output this is `void` or a no-value asynchronous type such as `Mono<Void>`.
|===

The table below shows all input and output cardinality combinations and the corresponding
interaction type(s):

[%autowidth]
[cols=3*,options="header"]
|===
| Input Cardinality
| Output Cardinality
| Interaction Types

| 0, 1
| 0
| Fire-and-Forget, Request-Response

| 0, 1
| 1
| Request-Response

| 0, 1
| Many
| Request-Stream

| Many
| 0, 1, Many
| Request-Channel

|===



[[rsocket-annot-connectmapping]]
=== @ConnectMapping

`@ConnectMapping` handles the `SETUP` frame at the start of an RSocket connection, and
any subsequent metadata push notifications through the `METADATA_PUSH` frame, i.e.
`metadataPush(Payload)` in `io.rsocket.RSocket`.

`@ConnectMapping` methods support the same arguments as
xref:rsocket:rsocket-annot-responders:rsocket-annot-messagemapping.adoc#rsocket-annot-messagemapping[rsocket-annot-messagemapping] but based on metadata and data from the `SETUP` and
`METADATA_PUSH` frames. `@ConnectMapping` can have a pattern to narrow handling to
specific connections that have a route in the metadata, or if no patterns are declared
then all connections match.

`@ConnectMapping` methods cannot return data and must be declared with `void` or
`Mono<Void>` as the return value. If handling returns an error for a new
connection then the connection is rejected. Handling must not be held up to make
requests to the `RSocketRequester` for the connection. See
xref:rsocket:rsocket-requester:rsocket-requester-server.adoc#rsocket-requester-server[rsocket-requester-server] for details.




