include::page$attributes.adoc[]
[[oxm-introduction]]
=== Introduction

This chapter, describes Spring's Object-XML Mapping support. Object-XML
Mapping (O-X mapping for short) is the act of converting an XML document to and from
an object. This conversion process is also known as XML Marshalling, or XML
Serialization. This chapter uses these terms interchangeably.

Within the field of O-X mapping, a marshaller is responsible for serializing an
object (graph) to XML. In similar fashion, an unmarshaller deserializes the XML to
an object graph. This XML can take the form of a DOM document, an input or output
stream, or a SAX handler.

Some of the benefits of using Spring for your O/X mapping needs are:

* xref:oxm:oxm-introduction:oxm-ease-of-configuration.adoc#oxm-ease-of-configuration[oxm-ease-of-configuration]
* xref:oxm:oxm-introduction:oxm-consistent-interfaces.adoc#oxm-consistent-interfaces[oxm-consistent-interfaces]
* xref:oxm:oxm-introduction:oxm-consistent-exception-hierarchy.adoc#oxm-consistent-exception-hierarchy[oxm-consistent-exception-hierarchy]


[[oxm-ease-of-configuration]]
==== Ease of configuration

Spring's bean factory makes it easy to configure marshallers, without needing to
construct JAXB context, JiBX binding factories, and so on. You can configure the marshallers
as you would any other bean in your application context. Additionally, XML namespace-based
configuration is available for a number of marshallers, making the configuration even
simpler.


[[oxm-consistent-interfaces]]
==== Consistent Interfaces

Spring's O-X mapping operates through two global interfaces: {api-spring-framework}/oxm/Marshaller.html[`Marshaller`] and
{api-spring-framework}/oxm/Unmarshaller.html[`Unmarshaller`]. These abstractions let you switch O-X mapping frameworks
with relative ease, with little or no change required on the classes that do the
marshalling. This approach has the additional benefit of making it possible to do XML
marshalling with a mix-and-match approach (for example, some marshalling performed using JAXB
and some by XStream) in a non-intrusive fashion, letting you use the strength of each
technology.


[[oxm-consistent-exception-hierarchy]]
==== Consistent Exception Hierarchy

Spring provides a conversion from exceptions from the underlying O-X mapping tool to its
own exception hierarchy with the `XmlMappingException` as the root exception.
These runtime exceptions wrap the original exception so that no information is lost.



