include::page$attributes.adoc[]
[[jdbc-packages]]
=== Package Hierarchy

The Spring Framework's JDBC abstraction framework consists of four different packages:

* `core`: The `org.springframework.jdbc.core` package contains the `JdbcTemplate` class and its
various callback interfaces, plus a variety of related classes. A subpackage named
`org.springframework.jdbc.core.simple` contains the `SimpleJdbcInsert` and
`SimpleJdbcCall` classes. Another subpackage named
`org.springframework.jdbc.core.namedparam` contains the `NamedParameterJdbcTemplate`
class and the related support classes. See xref:jdbc:jdbc-core.adoc#jdbc-core[jdbc-core], xref:jdbc:jdbc-advanced-jdbc.adoc#jdbc-advanced-jdbc[jdbc-advanced-jdbc], and
xref:jdbc:jdbc-simple-jdbc.adoc#jdbc-simple-jdbc[jdbc-simple-jdbc].

* `datasource`: The `org.springframework.jdbc.datasource` package contains a utility class for easy
`DataSource` access and various simple `DataSource` implementations that you can use for
testing and running unmodified JDBC code outside of a Java EE container. A subpackage
named `org.springfamework.jdbc.datasource.embedded` provides support for creating
embedded databases by using Java database engines, such as HSQL, H2, and Derby. See
xref:jdbc:jdbc-connections.adoc#jdbc-connections[jdbc-connections] and xref:jdbc:jdbc-embedded-database-support.adoc#jdbc-embedded-database-support[jdbc-embedded-database-support].

* `object`: The `org.springframework.jdbc.object` package contains classes that represent RDBMS
queries, updates, and stored procedures as thread-safe, reusable objects. See
xref:jdbc:jdbc-object.adoc#jdbc-object[jdbc-object]. This approach is modeled by JDO, although objects returned by queries
are naturally disconnected from the database. This higher-level of JDBC abstraction
depends on the lower-level abstraction in the `org.springframework.jdbc.core` package.

* `support`: The `org.springframework.jdbc.support` package provides `SQLException` translation
functionality and some utility classes. Exceptions thrown during JDBC processing are
translated to exceptions defined in the `org.springframework.dao` package. This means
that code using the Spring JDBC abstraction layer does not need to implement JDBC or
RDBMS-specific error handling. All translated exceptions are unchecked, which gives you
the option of catching the exceptions from which you can recover while letting other
exceptions be propagated to the caller. See xref:jdbc:jdbc-core:jdbc-NamedParameterJdbcTemplate.adoc#jdbc-SQLExceptionTranslator[jdbc-SQLExceptionTranslator].



